### ISSUE TITLE
Add "homepage" to opscode metadata

### ISSUE THREAD

**Issue by mansona** [digitalbutter/cookbook-node#13]
Hey guys, took me a little while to find this github profile because i was looking for the homepage meta data at the top of the opscode community site. I don't know how to update that but it would be worth adding the link that is in your readme to that metadata. 

Example: https://cloudup.com/c7yt3yJJuyQ

**Comment by edbo** [comment]
Hi Mansona,

I actually tried to set this but I couldn't figure out where to do it. Don't know if you have any ideas.
