### ISSUE TITLE
build-essential (make) dependency not included

### ISSUE THREAD

**Issue by togume** [digitalbutter/cookbook-node#14]
While using Chef, Berkshelf, AWS, etc, I got an error while installing the node cookbook because 'make' was not found. This is part of the build-essential community cookbook.

Best AFAIK practice is to:
- Include the dependency in the metadata.rb/json
- Include the "build-essential::default" in a recipe

Let me know if there's something I'm missing, or if there are any questions! I'll try to look into this myself when time permits :).

**Comment by edbo** [comment]
Added here: dfad36d872294b4f7287e3b711cb99575b729e32
