### ISSUE TITLE
node_service action :start doesn't work if process is already running

### ISSUE THREAD

**Issue by xentac** [digitalbutter/cookbook-node#2]
I'm a little new to chef, but I think this is an error.  Because the action :start, :stop, and :restart parts of the provider just call exec, they can fail if the service is already running.

My application recipe includes a node_service section and I'm pretty sure I want it to be action :start, but that doesn't work because the exec fails if the process is already running.

I have a series of changes that make it use the upstart service properly so that subsequent runs of chef-client don't error out.

Am I correct in my thinking?

**Comment by eprochasson** [comment]
You are correct. I'm taking a look at your pull request, it looks much nicer (actually, I fixed it by calling ":restart" in the recipe instead of ":start", your approach is much more elegant).
