### ISSUE TITLE
Version bump for opscode site

### ISSUE THREAD

**Issue by lukeasrodgers** [digitalbutter/cookbook-node#9]
A version bump on the [Opscode site](http://community.opscode.com/cookbooks/node) would be great so that f2641f7d3d5f29c06e1d4a2cae4dfa8388cec21e is automatically pulled in.

Thanks

**Comment by edbo** [comment]
Did this now. Although I found another node cookbook here that I might try out:

http://community.opscode.com/cookbooks/nodejs

 It looks like it has a bit more activity than this one.
